### ISSUE TITLE
Missing SecureStorage

### ISSUE THREAD

**Issue by sanderDijkxhoorn** [BitBoxLab-OU/Crypto-Messenger#2]

**Comment by Andrea-Bruno** [comment]
The secure storage is here
https://github.com/BitBoxLab-OU/Secure-Storage

**Comment by sanderDijkxhoorn** [comment]
I compiled it and got EncryptedMessaging.dll, CommunicationChannel.dll & SecureStorage.dll what am I supposed to do with this?

**Comment by Andrea-Bruno** [comment]
Encrypted Messaging is a library that can be used to create Telegram or
Signal type messaging software.  This week we will be releasing demo
software with the user interface, which uses this library.  We are also
completing the manuals.  It is a new project, released 3 days ago, we have
not yet had the time to publish the demonstrations

Il sab 4 dic 2021, 00:18 Sander Dijkxhoorn ***@***.***> ha
scritto:
